import Submission.MyLeanRepo.Kakeya.Assouad.PureWZ2.Prop62AncestryPreliminarySelection
import Submission.MyLeanRepo.Kakeya.Assouad.PureWZ2.Prop62MetricPacketProducer

/-!
# Proposition 6.2: metric packet hull after per-cell ancestry selection

The complete packet hull is generated by the per-cell ancestry selection, not
by a single global ancestry color.  That selected class is saturated for the
old `s`-parent map: an `s`-packet fixes its line cell and every older parent,
hence fixes its upper conflict-color vector.  Completing the selected old
parents therefore returns exactly the per-cell selected class.
-/

noncomputable section

namespace Kakeya.Assouad

attribute [local instance] Classical.propDecidable

namespace PureWZ2Prop62AncestryPreliminarySelectionData

variable
    {delta : ℝ}
    {fine : Kakeya.Streamlined.TubeFamily delta}
    {ambientConstant scaleWindow : ENNReal}
    {schedule :
      PureWZ2Prop62PureSchedule
        fine ambientConstant scaleWindow}
    {scheduled :
      PureWZ2Prop62ScheduledParentColoringData schedule}
    {rho width : ℝ}
    {packetCoordinate : Fin schedule.levelCount}
    {coordinateCount : ℕ}
    {Color : Fin coordinateCount → Type*}
    [∀ coordinate, Fintype (Color coordinate)]
    [∀ coordinate, DecidableEq (Color coordinate)]
    [∀ coordinate, Nonempty (Color coordinate)]
    {color : ∀ coordinate, Fin fine.card → Color coordinate}
    {weight : Fin fine.card → ENNReal}
    (data :
      PureWZ2Prop62AncestryPreliminarySelectionData
        schedule scheduled rho width packetCoordinate
        Color color weight)

theorem perCell_selected_packet_saturated
    (first second : Fin fine.card)
    (packetParentEq :
      (schedule.scaleData packetCoordinate).cover.parent first =
        (schedule.scaleData packetCoordinate).cover.parent second) :
    first ∈ data.perCell.selected ↔
      second ∈ data.perCell.selected := by
  have cellValueEq :
      schedule.packetLineCell packetCoordinate width first =
        schedule.packetLineCell packetCoordinate width second :=
    schedule.packetLineCell_parent_invariant
      packetCoordinate width first second packetParentEq
  have cellEq :
      PureWZ2Prop62PureSchedule.packetCell
          (schedule.packetLineCell packetCoordinate width) first =
        PureWZ2Prop62PureSchedule.packetCell
          (schedule.packetLineCell packetCoordinate width) second := by
    apply Subtype.ext
    exact cellValueEq
  have colorEq :
      schedule.upperColorVector scheduled rho packetCoordinate first =
        schedule.upperColorVector scheduled rho packetCoordinate second := by
    funext coordinate
    unfold PureWZ2Prop62PureSchedule.upperColorVector
    unfold PureWZ2Prop62ScheduledParentColoringData.leafColor
    congr 1
    exact
      schedule.parent_eq_of_coordinate_le
        coordinate.1 packetCoordinate
        (by
          exact Nat.le_of_lt coordinate.2.2)
        first second packetParentEq
  have residueEq :
      pureWZ2Prop62LineColor width (data.residueStrideBase + 1)
            ((schedule.scaleData packetCoordinate).coarse.tube
              ((schedule.scaleData packetCoordinate).cover.parent first)) =
        pureWZ2Prop62LineColor width (data.residueStrideBase + 1)
          ((schedule.scaleData packetCoordinate).coarse.tube
            ((schedule.scaleData packetCoordinate).cover.parent second)) := by
    rw [packetParentEq]
  rw [data.perCell.selected_eq]
  simp only [Finset.mem_filter, Finset.mem_univ, true_and]
  rw [residueEq, cellEq, colorEq]

def selectedOldParents :
    Finset
      (Fin (schedule.scaleData packetCoordinate).coarse.card) :=
  data.perCell.selected.image
    (schedule.scaleData packetCoordinate).cover.parent

theorem selectedOldParents_nonempty :
    data.selectedOldParents.Nonempty := by
  rcases data.preliminary.selected_nonempty with
    ⟨source, sourceMem⟩
  have sourcePerCell :=
    data.selected_subset_perCell sourceMem
  exact
    ⟨(schedule.scaleData packetCoordinate).cover.parent source,
      Finset.mem_image.mpr
        ⟨source, sourcePerCell, rfl⟩⟩

theorem selectedOldParents_sameResidue
    (first second :
      Fin (schedule.scaleData packetCoordinate).coarse.card)
    (firstMem : first ∈ data.selectedOldParents)
    (secondMem : second ∈ data.selectedOldParents) :
    pureWZ2Prop62LineColor width (data.residueStrideBase + 1)
          ((schedule.scaleData packetCoordinate).coarse.tube first) =
      pureWZ2Prop62LineColor width (data.residueStrideBase + 1)
        ((schedule.scaleData packetCoordinate).coarse.tube second) := by
  rcases Finset.mem_image.mp firstMem with
    ⟨firstSource, firstSourceMem, firstEq⟩
  rcases Finset.mem_image.mp secondMem with
    ⟨secondSource, secondSourceMem, secondEq⟩
  have firstResidue :=
    data.perCell.selected_residue firstSource firstSourceMem
  have secondResidue :=
    data.perCell.selected_residue secondSource secondSourceMem
  simpa only [firstEq, secondEq] using
    firstResidue.trans secondResidue.symm

end PureWZ2Prop62AncestryPreliminarySelectionData

structure PureWZ2Prop62AncestryMetricPreliminaryOutput
    {delta rho : ℝ}
    {fine : Kakeya.Streamlined.TubeFamily delta}
    {ambientConstant scaleWindow : ENNReal}
    (schedule :
      PureWZ2Prop62PureSchedule
        fine ambientConstant scaleWindow)
    (scheduled :
      PureWZ2Prop62ScheduledParentColoringData schedule)
    (width : ℝ)
    (packetCoordinate : Fin schedule.levelCount)
    {coordinateCount : ℕ}
    (Color : Fin coordinateCount → Type*)
    [∀ coordinate, Fintype (Color coordinate)]
    [∀ coordinate, DecidableEq (Color coordinate)]
    [∀ coordinate, Nonempty (Color coordinate)]
    (color : ∀ coordinate, Fin fine.card → Color coordinate)
    (weight : Fin fine.card → ENNReal)
    (preliminary :
      PureWZ2Prop62AncestryPreliminarySelectionData
        schedule scheduled rho width packetCoordinate
        Color color weight)
    (M : ℝ) where
  metric :
    PureWZ2Prop62MetricPacketOutput
      (rho := rho)
      (schedule.scaleData packetCoordinate) width M
  metric_parents_eq :
    metric.selectedParents = preliminary.selectedOldParents
  packet_hull_eq_perCell :
    metric.mesh.complete.selectedFineIndices =
      preliminary.perCell.selected
  selectedPreliminary :
    Finset (Fin metric.selectedFine.card)
  selectedPreliminary_eq :
    selectedPreliminary =
      Finset.univ.filter fun source =>
        metric.mesh.complete.selectedFine.embedding source ∈
          preliminary.preliminary.selected
  selectedPreliminary_nonempty :
    selectedPreliminary.Nonempty
  selectedPreliminary_image_eq :
    Finset.image metric.mesh.complete.selectedFine.embedding
        selectedPreliminary =
      preliminary.preliminary.selected

theorem pureWZ2_prop62_ancestry_metric_preliminary_output
    {delta rho : ℝ}
    {fine : Kakeya.Streamlined.TubeFamily delta}
    {ambientConstant scaleWindow : ENNReal}
    (schedule :
      PureWZ2Prop62PureSchedule
        fine ambientConstant scaleWindow)
    (scheduled :
      PureWZ2Prop62ScheduledParentColoringData schedule)
    (width : ℝ)
    (packetCoordinate : Fin schedule.levelCount)
    {coordinateCount : ℕ}
    (Color : Fin coordinateCount → Type*)
    [∀ coordinate, Fintype (Color coordinate)]
    [∀ coordinate, DecidableEq (Color coordinate)]
    [∀ coordinate, Nonempty (Color coordinate)]
    (color : ∀ coordinate, Fin fine.card → Color coordinate)
    (weight : Fin fine.card → ENNReal)
    (preliminary :
      PureWZ2Prop62AncestryPreliminarySelectionData
        schedule scheduled rho width packetCoordinate
        Color color weight)
    (M : ℝ)
    (rhoPos : 0 < rho)
    (fineNonempty : fine.Nonempty)
    (fineLine : WZ1PaperIsLineClass fine)
    (fineLocal :
      ∀ source,
        ‖wz2PaperTubeMidpoint (fine.tube source)‖ ≤ M)
    (widthPos : 0 < width)
    (strongSeparation :
      360 * rho <
        (((preliminary.residueStrideBase + 1 : ℕ) : ℝ) - 1) * width)
    (packetBound :
      (16 * M + 44) *
            schedule.actualScale packetCoordinate +
          6 * width ≤ rho / 2) :
    Nonempty
      (PureWZ2Prop62AncestryMetricPreliminaryOutput
        schedule scheduled width packetCoordinate
        Color color weight preliminary M) := by
  let selectedParents := preliminary.selectedOldParents
  rcases
      pureWZ2_prop62_metric_packet_output
        (schedule.scaleData packetCoordinate)
        width M rhoPos fineNonempty fineLine fineLocal
        selectedParents preliminary.selectedOldParents_nonempty
        widthPos (preliminary.residueStrideBase + 1)
        preliminary.selectedOldParents_sameResidue
        strongSeparation packetBound
        (schedule.coarse_line_class packetCoordinate)
    with
    ⟨metric, metricParents⟩
  have hullEq :
      metric.mesh.complete.selectedFineIndices =
        preliminary.perCell.selected := by
    ext source
    simp only [
      PureWZ2CompleteParentRestrictionData.selectedFineIndices,
      Finset.mem_filter, Finset.mem_univ, true_and
    ]
    constructor
    · intro parentMem
      rw [metric.mesh_selectedParents_eq, metricParents] at parentMem
      rcases Finset.mem_image.mp parentMem with
        ⟨witness, witnessMem, parentEq⟩
      exact
        (preliminary.perCell_selected_packet_saturated
          witness source parentEq).mp witnessMem
    · intro sourceMem
      rw [metric.mesh_selectedParents_eq, metricParents]
      exact
        Finset.mem_image.mpr
          ⟨source, sourceMem, rfl⟩
  have selectedSubsetHull :
      preliminary.preliminary.selected ⊆
        metric.mesh.complete.selectedFineIndices := by
    rw [hullEq]
    exact preliminary.selected_subset_perCell
  let selectedPreliminary :
      Finset (Fin metric.selectedFine.card) :=
    Finset.univ.filter fun source =>
      metric.mesh.complete.selectedFine.embedding source ∈
        preliminary.preliminary.selected
  have selectedPreliminaryNonempty :
      selectedPreliminary.Nonempty := by
    rcases preliminary.preliminary.selected_nonempty with
      ⟨ambientSource, sourceMem⟩
    have sourceHull := selectedSubsetHull sourceMem
    rcases
        metric.mesh.complete.selectedFine_ambient_surjective
          ambientSource sourceHull
      with
      ⟨source, sourceEq⟩
    exact
      ⟨source,
        Finset.mem_filter.mpr
          ⟨Finset.mem_univ source, by
            rwa [sourceEq]⟩⟩
  have selectedImage :
      Finset.image metric.mesh.complete.selectedFine.embedding
          selectedPreliminary =
        preliminary.preliminary.selected := by
    ext ambientSource
    constructor
    · intro sourceImage
      rcases Finset.mem_image.mp sourceImage with
        ⟨source, sourceMem, sourceEq⟩
      have ambientMem :=
        (Finset.mem_filter.mp sourceMem).2
      rwa [sourceEq] at ambientMem
    · intro sourceMem
      have sourceHull := selectedSubsetHull sourceMem
      rcases
          metric.mesh.complete.selectedFine_ambient_surjective
            ambientSource sourceHull
        with
        ⟨source, sourceEq⟩
      exact
        Finset.mem_image.mpr
          ⟨source,
            Finset.mem_filter.mpr
              ⟨Finset.mem_univ source, by
                rwa [sourceEq]⟩,
            sourceEq⟩
  exact
    ⟨{
      metric := metric
      metric_parents_eq := metricParents
      packet_hull_eq_perCell := hullEq
      selectedPreliminary := selectedPreliminary
      selectedPreliminary_eq := rfl
      selectedPreliminary_nonempty := selectedPreliminaryNonempty
      selectedPreliminary_image_eq := selectedImage
    }⟩

namespace PureWZ2Prop62AncestryMetricPreliminaryOutput

variable
    {delta rho : ℝ}
    {fine : Kakeya.Streamlined.TubeFamily delta}
    {ambientConstant scaleWindow : ENNReal}
    {schedule :
      PureWZ2Prop62PureSchedule
        fine ambientConstant scaleWindow}
    {scheduled :
      PureWZ2Prop62ScheduledParentColoringData schedule}
    {width : ℝ}
    {packetCoordinate : Fin schedule.levelCount}
    {coordinateCount : ℕ}
    {Color : Fin coordinateCount → Type*}
    [∀ coordinate, Fintype (Color coordinate)]
    [∀ coordinate, DecidableEq (Color coordinate)]
    [∀ coordinate, Nonempty (Color coordinate)]
    {color : ∀ coordinate, Fin fine.card → Color coordinate}
    {weight : Fin fine.card → ENNReal}
    {preliminary :
      PureWZ2Prop62AncestryPreliminarySelectionData
        schedule scheduled rho width packetCoordinate
        Color color weight}
    {M : ℝ}
    (output :
      PureWZ2Prop62AncestryMetricPreliminaryOutput
        schedule scheduled width packetCoordinate
        Color color weight preliminary M)

theorem sourceCell_eq_packetLineCell_embedding
    (source : Fin output.metric.selectedFine.card) :
    output.metric.mesh.sourceCell source =
      schedule.packetLineCell packetCoordinate width
        (output.metric.mesh.complete.selectedFine.embedding source) := by
  rfl

theorem metricParent_eq_iff_packetLineCell_embedding_eq
    (first second : Fin output.metric.selectedFine.card) :
    output.metric.metricInput.packetParent
          (output.metric.mesh.restrictedOldData.cover.parent first) =
        output.metric.metricInput.packetParent
          (output.metric.mesh.restrictedOldData.cover.parent second) ↔
      schedule.packetLineCell packetCoordinate width
          (output.metric.mesh.complete.selectedFine.embedding first) =
        schedule.packetLineCell packetCoordinate width
          (output.metric.mesh.complete.selectedFine.embedding second) := by
  rw [
    output.metric.metricInput_packetParent_eq_iff_sourceCell_eq,
    output.sourceCell_eq_packetLineCell_embedding,
    output.sourceCell_eq_packetLineCell_embedding
  ]

end PureWZ2Prop62AncestryMetricPreliminaryOutput

end Kakeya.Assouad

end
