import Submission.MyLeanRepo.Kakeya.Assouad.WZ1.Lemma23LocalizedPreparedGeometry
import Submission.MyLeanRepo.Kakeya.Assouad.WZ1.Lemma23Theorem22ReadyGraph

/-!
# Common-endpoint Theorem-22 graph for WZ1 Lemma 23

Both actual endpoint classes are images of the same local-point map on the
same y-residue cells.  This module enlarges them to that common ambient set
before the final `/5` normalization.  The actual edge set and its
dot-difference values are unchanged.
-/

namespace Kakeya.Assouad

noncomputable section

/-- All local graph vertices generated by the selected residue cells. -/
def wz1Lemma23CommonLocalVertices
    (rho : ℝ) (g : ℝ → ℝ)
    (cells : Finset (ℤ × ℤ × ℤ)) : DiscreteSet 2 :=
  cells.image (wz1Lemma23SnappedLocalPoint rho g)

/-- The sharp Lemma-23 graph with one common ambient endpoint class. -/
theorem WZ1Lemma23LocalizedPreparedGeometry.toCommonEndpointGraph
    {delta rho sigma : ℝ}
    {F : Kakeya.Streamlined.TubeFamily delta}
    {Y : Kakeya.Streamlined.TubeShading F}
    {C : ENNReal}
    {windowed :
      WZ1Lemma23WindowedGlobalSlicePackage
        (delta := delta) (rho := rho) (sigma := sigma) Y C}
    {localized : WZ1Lemma23LocalizedGlobalBinPackage windowed.global}
    {residue : WZ1Lemma23YResiduePackage windowed.global}
    {localBins :
      WZ1Lemma23LocalBinPackage
        (rho := rho) (sigma := sigma) C windowed.global.cells}
    {prepared :
      WZ1Lemma23LocalizedPreparedPackage
        windowed localized residue localBins}
    (geometry : WZ1Lemma23LocalizedPreparedGeometry prepared)
    (hrho_one : rho ≤ 1)
    (hcoord : ∀ point ∈ Y.union, ∀ i : Fin 3, |point i| ≤ 1) :
    Nonempty
      (WZ1Lemma23UnitBallGraph
        rho prepared.normalized.F
        (wz1Lemma23CommonLocalVertices
          rho prepared.selectedLocal.g residue.cells)
        (wz1Lemma23CommonLocalVertices
          rho prepared.selectedLocal.g residue.cells)
        prepared.normalized.H) := by
  let common := wz1Lemma23CommonLocalVertices
    rho prepared.selectedLocal.g residue.cells
  have hcycleCells :
      ∀ path ∈ prepared.actual.cycles,
        path.1 ∈ residue.cells ∧ path.2.1 ∈ residue.cells ∧
          path.2.2.1 ∈ residue.cells ∧ path.2.2.2 ∈ residue.cells := by
    intro path hpath
    have hbase :
        path ∈ wz1Lemma23SnappedBaseCycles
          rho windowed.global.extendedSlope prepared.selectedLocal.g
          residue.cells prepared.baseHeightIndex prepared.baseGlobalBin := by
      rwa [prepared.actual.cycles_eq] at hpath
    have hfour :
        path ∈ wz1Lemma23SnappedFourCycles
          rho windowed.global.extendedSlope prepared.selectedLocal.g
          residue.cells := (Finset.mem_filter.mp hbase).1
    have hrelations :
        (path.1 ∈ residue.cells ∧ path.2.1 ∈ residue.cells ∧
          path.2.2.1 ∈ residue.cells ∧ path.2.2.2 ∈ residue.cells) ∧
        wz1Lemma23SameSnappedLocalGrain rho prepared.selectedLocal.g
          path.1 path.2.1 ∧
        wz1Lemma23SameSnappedLocalGrain rho prepared.selectedLocal.g
          path.2.2.2 path.2.2.1 ∧
        wz1Lemma23SnappedHeight path.1 =
          wz1Lemma23SnappedHeight path.2.2.2 ∧
        wz1Lemma23SnappedHeight path.2.1 =
          wz1Lemma23SnappedHeight path.2.2.1 ∧
        wz1Lemma23SnappedGlobalBin rho windowed.global.extendedSlope
          path.2.1 =
          wz1Lemma23SnappedGlobalBin rho windowed.global.extendedSlope
            path.2.2.1 := by
      simpa [wz1Lemma23SnappedFourCycles, wz1Lemma23FourCycles,
        Finset.mem_filter, Finset.mem_product] using hfour
    exact hrelations.1
  have hG₁subset : prepared.normalized.G₁ ⊆ common := by
    intro point hpoint
    rw [prepared.normalized.G₁_eq, prepared.normalized_sourceG₁,
      prepared.actual.G₁_eq] at hpoint
    rcases Finset.mem_image.mp hpoint with ⟨path, hpath, rfl⟩
    have hcell : path.1 ∈ residue.cells := (hcycleCells path hpath).1
    exact Finset.mem_image.mpr ⟨path.1, hcell, rfl⟩
  have hG₂subset : prepared.normalized.G₂ ⊆ common := by
    intro point hpoint
    rw [prepared.normalized.G₂_eq, prepared.normalized_sourceG₂,
      prepared.actual.G₂_eq] at hpoint
    rcases Finset.mem_image.mp hpoint with ⟨path, hpath, rfl⟩
    have hcell : path.2.2.1 ∈ residue.cells :=
      (hcycleCells path hpath).2.2.1
    exact Finset.mem_image.mpr ⟨path.2.2.1, hcell, rfl⟩
  have hsupport :
      ∀ edge ∈ prepared.normalized.H,
        edge.1 ∈ prepared.normalized.F ∧
          edge.2.1 ∈ common ∧ edge.2.2 ∈ common := by
    intro edge hedge
    have hs := prepared.normalized.edge_support edge hedge
    exact ⟨hs.1, hG₁subset hs.2.1, hG₂subset hs.2.2⟩
  have hcommonBound : ∀ point ∈ common, dist point 0 ≤ 5 := by
    intro point hpoint
    rcases Finset.mem_image.mp hpoint with ⟨cell, hcell, rfl⟩
    simpa [dist_zero_right] using
      wz1Lemma23_local_point_bound_of_coord
        windowed.global.rho_pos hrho_one hcoord
        prepared.selectedLocal.g prepared.selectedLocal.g_bounded
        (residue.cells_active hcell)
  have hcommonCoord :
      ∀ first ∈ common, ∀ second ∈ common, first ≠ second →
        Real.sqrt rho / Real.sqrt 3 ≤ |first 1 - second 1| := by
    intro first hfirst second hsecond hne
    rcases Finset.mem_image.mp hfirst with ⟨firstCell, hfirstCell, rfl⟩
    rcases Finset.mem_image.mp hsecond with ⟨secondCell, hsecondCell, rfl⟩
    have hroot := wz1Lemma23_local_points_coordinate_separated
      prepared.selectedLocal.g residue.y_separated
      hfirstCell hsecondCell hne
    exact (div_le_self (Real.sqrt_nonneg rho)
      ((Real.one_le_sqrt).2 (by norm_num))).trans hroot
  rcases geometry.vertex_bounds with ⟨hFbound, _, _⟩
  rcases geometry.coordinate_separation with ⟨hFcoord, _, _⟩
  exact wz1_lemma23_unit_ball_graph windowed.global.rho_pos
    hsupport hFbound hcommonBound hcommonBound
    hFcoord hcommonCoord hcommonCoord

end

/-- Attach the unchanged edge threshold and Katz--Tao absorption to the
common-endpoint graph. -/
theorem WZ1Lemma23LocalizedPreparedGeometry.toCommonEndpointReadyGraph
    {delta rho sigma theoremEta : ℝ}
    {F : Kakeya.Streamlined.TubeFamily delta}
    {Y : Kakeya.Streamlined.TubeShading F}
    {C : ENNReal}
    {windowed :
      WZ1Lemma23WindowedGlobalSlicePackage
        (delta := delta) (rho := rho) (sigma := sigma) Y C}
    {localized : WZ1Lemma23LocalizedGlobalBinPackage windowed.global}
    {residue : WZ1Lemma23YResiduePackage windowed.global}
    {localBins :
      WZ1Lemma23LocalBinPackage
        (rho := rho) (sigma := sigma) C windowed.global.cells}
    {prepared :
      WZ1Lemma23LocalizedPreparedPackage
        windowed localized residue localBins}
    (geometry : WZ1Lemma23LocalizedPreparedGeometry prepared)
    (hrho_one : rho ≤ 1)
    (hcoord : ∀ point ∈ Y.union, ∀ i : Fin 3, |point i| ≤ 1)
    (hedge :
      Kakeya.realRpowENN (wz1Lemma23Theorem22Scale rho)
          (theoremEta - 3) ≤
        (geometry.unitBall.H.card : ENNReal))
    (hKatzTaoConstant :
      (4 : ENNReal) ≤
        Kakeya.realRpowENN
          (wz1Lemma23Theorem22Scale rho) (-theoremEta)) :
    ∃ common :
        WZ1Lemma23UnitBallGraph
          rho prepared.normalized.F
          (wz1Lemma23CommonLocalVertices
            rho prepared.selectedLocal.g residue.cells)
          (wz1Lemma23CommonLocalVertices
            rho prepared.selectedLocal.g residue.cells)
          prepared.normalized.H,
      Nonempty
        (WZ1Lemma23Theorem22ReadyGraph
          rho theoremEta common) := by
  rcases geometry.toCommonEndpointGraph hrho_one hcoord with ⟨common⟩
  have hedgeCommon :
      Kakeya.realRpowENN (wz1Lemma23Theorem22Scale rho)
          (theoremEta - 3) ≤
        (common.H.card : ENNReal) := by
    have hedgeSource :
        Kakeya.realRpowENN (wz1Lemma23Theorem22Scale rho)
            (theoremEta - 3) ≤
          (prepared.normalized.H.card : ENNReal) := by
      rw [geometry.unitBall.edge_card] at hedge
      exact hedge
    rw [common.edge_card]
    exact hedgeSource
  let deltaGraph := wz1Lemma23Theorem22Scale rho
  have hdeltaGraph : 0 < deltaGraph := by
    dsimp only [deltaGraph, wz1Lemma23Theorem22Scale]
    exact div_pos (Real.sqrt_pos.mpr windowed.global.rho_pos)
      (by positivity)
  have hthresholdPos :
      0 < Kakeya.realRpowENN deltaGraph (theoremEta - 3) := by
    apply ENNReal.ofReal_pos.mpr
    exact Real.rpow_pos_of_pos hdeltaGraph _
  have hHcardPos : 0 < (common.H.card : ENNReal) :=
    hthresholdPos.trans_le hedgeCommon
  have hHnonempty : common.H.Nonempty := by
    apply Finset.card_pos.mp
    exact_mod_cast hHcardPos
  rcases hHnonempty with ⟨edge, hedgeMem⟩
  have hsupport := common.edge_support edge hedgeMem
  let ready : WZ1Lemma23Theorem22ReadyGraph rho theoremEta common :=
    { deltaGraph := deltaGraph
      deltaGraph_eq := rfl
      deltaGraph_pos := hdeltaGraph
      F_nonempty := ⟨edge.1, hsupport.1⟩
      G₁_nonempty := ⟨edge.2.1, hsupport.2.1⟩
      G₂_nonempty := ⟨edge.2.2, hsupport.2.2⟩
      H_nonempty := ⟨edge, hedgeMem⟩
      F_katzTao := common.F_katzTao.mono_const hKatzTaoConstant
      G₁_katzTao := common.G₁_katzTao.mono_const hKatzTaoConstant
      G₂_katzTao := common.G₂_katzTao.mono_const hKatzTaoConstant
      edge_threshold := hedgeCommon }
  exact ⟨common, ⟨ready⟩⟩

end Kakeya.Assouad
