import Submission.MyLeanRepo.Kakeya.Assouad.WZ1.Lemma23DotDifferenceStatements

/-!
# Encode WZ1 Lemma 23 four-cycles as tripartite edges

After the geometric four-cycle construction, the paper maps
`(Q₁,Q₂,Q₃,Q₄)` to the projection-theorem edge

`(F(Q₂), G(Q₁), G(Q₃))`.

The geometric argument must prove that this map is injective on the retained
four-cycles.  This module performs the remaining finite bookkeeping: the
edge count is preserved, every edge is supported in the three image vertex
classes, and its dot-difference set is exactly the image of the pointwise
four-cycle dot values.
-/

namespace Kakeya.Assouad

noncomputable section

/-- The projection-theorem edge encoded by one Lemma 23 four-cycle. -/
def wz1Lemma23TripartiteEdge
    {Cube : Type*}
    (heightPoint localPoint : Cube → Point2)
    (path : Cube × Cube × Cube × Cube) :
    Point2 × Point2 × Point2 :=
  (heightPoint path.2.1, localPoint path.1, localPoint path.2.2.1)

/-- The first vertex class generated by the second cube of every path. -/
def wz1Lemma23HeightVertices
    {Cube : Type*} [DecidableEq Cube]
    (cycles : Finset (Cube × Cube × Cube × Cube))
    (heightPoint : Cube → Point2) : DiscreteSet 2 :=
  cycles.image fun path => heightPoint path.2.1

/-- The second vertex class generated by the first cube of every path. -/
def wz1Lemma23FirstLocalVertices
    {Cube : Type*} [DecidableEq Cube]
    (cycles : Finset (Cube × Cube × Cube × Cube))
    (localPoint : Cube → Point2) : DiscreteSet 2 :=
  cycles.image fun path => localPoint path.1

/-- The third vertex class generated by the third cube of every path. -/
def wz1Lemma23ThirdLocalVertices
    {Cube : Type*} [DecidableEq Cube]
    (cycles : Finset (Cube × Cube × Cube × Cube))
    (localPoint : Cube → Point2) : DiscreteSet 2 :=
  cycles.image fun path => localPoint path.2.2.1

/-- The finite tripartite graph generated by the retained four-cycles. -/
def wz1Lemma23TripartiteEdges
    {Cube : Type*} [DecidableEq Cube]
    (cycles : Finset (Cube × Cube × Cube × Cube))
    (heightPoint localPoint : Cube → Point2) :
    Finset (Point2 × Point2 × Point2) :=
  cycles.image (wz1Lemma23TripartiteEdge heightPoint localPoint)

/-- The pointwise dot-difference values generated by the retained paths. -/
def wz1Lemma23FourCycleDotValues
    {Cube : Type*} [DecidableEq Cube]
    (cycles : Finset (Cube × Cube × Cube × Cube))
    (heightPoint localPoint : Cube → Point2) : Finset ℝ :=
  cycles.image fun path =>
    inner ℝ (heightPoint path.2.1)
      (localPoint path.1 - localPoint path.2.2.1)

/--
Exact finite bookkeeping for the Lemma 23 tripartite encoding.

Injectivity is explicit because it is the geometric reason that the large
four-cycle count survives as the cardinality lower bound required by
Theorem 22.
-/
lemma wz1_lemma23_tripartite_encoding
    {Cube : Type*} [DecidableEq Cube]
    (cycles : Finset (Cube × Cube × Cube × Cube))
    (heightPoint localPoint : Cube → Point2)
    (hinjective :
      Set.InjOn
        (wz1Lemma23TripartiteEdge heightPoint localPoint)
        cycles) :
    let F := wz1Lemma23HeightVertices cycles heightPoint
    let G₁ := wz1Lemma23FirstLocalVertices cycles localPoint
    let G₂ := wz1Lemma23ThirdLocalVertices cycles localPoint
    let H := wz1Lemma23TripartiteEdges cycles heightPoint localPoint
    let values :=
      wz1Lemma23FourCycleDotValues cycles heightPoint localPoint
    H.card = cycles.card ∧
      (∀ edge ∈ H,
        edge.1 ∈ F ∧ edge.2.1 ∈ G₁ ∧ edge.2.2 ∈ G₂) ∧
      wz1DotDifferenceSet H = (values : Set ℝ) := by
  classical
  dsimp only
  constructor
  · exact Finset.card_image_of_injOn hinjective
  constructor
  · intro edge hedge
    rcases Finset.mem_image.mp hedge with ⟨path, hpath, rfl⟩
    exact
      ⟨Finset.mem_image.mpr ⟨path, hpath, rfl⟩,
        Finset.mem_image.mpr ⟨path, hpath, rfl⟩,
        Finset.mem_image.mpr ⟨path, hpath, rfl⟩⟩
  · ext value
    simp [wz1DotDifferenceSet, wz1Lemma23TripartiteEdges,
      wz1Lemma23FourCycleDotValues, wz1Lemma23TripartiteEdge]

end

end Kakeya.Assouad
