import Submission.MyLeanRepo.Kakeya.Assouad.PureWZ2.C2.PureHierarchyReentrantOrdinaryFrontEnd
import Submission.MyLeanRepo.Kakeya.Assouad.PureWZ2.C2.PureHierarchyReentrantOrdinaryScalarClosure
import Submission.MyLeanRepo.Kakeya.Assouad.PureWZ2.C2.SourceHorizontalOuterScale
import Submission.MyLeanRepo.Kakeya.Assouad.PureWZ2.C2.Node05OwnerTwoCallAssembly
import Submission.MyLeanRepo.Kakeya.Assouad.PureWZ2.C2.Node05SynchronizedSecondOwnerCall
import Submission.MyLeanRepo.Kakeya.Assouad.PureWZ2.C2.OrdinaryAllBinPopularCoarsePreparation
import Submission.MyLeanRepo.Kakeya.Assouad.PureWZ2.C2.SourceFixedLineCoarseAnalyticThreshold
import Submission.MyLeanRepo.Kakeya.Assouad.PureWZ2.C2.SourceFixedLineCoarseProjectionThreshold
import Submission.MyLeanRepo.Kakeya.Assouad.PureWZ2.C2.SourceFixedLineCoarseExactMassBudget

/-!
# Actual-owner front end for the re-entrant ordinary hierarchy

This module selects the scalar schedules which are already available before
the runtime source.  At runtime the public re-entry kernel constructs its
first exact sticky seed on `current.grain.shading`.  The owner-side input left
explicit is the dependent upgrade of that exact seed to the two Node-5 owner
calls.  After that exact chain has been selected, the paper-facing geometric
boundary consists of the source-`rho` slab AD receipt and the joint
outer-popular genuine-coarse graph-volume receipt.  A separate completed
receipt records the still-unproved construction of the final one-scale output.
The scalar receipt for the synchronized step is generated by the schedule
itself.

There is intentionally no selected-family nearby-CWA input or conclusion in
this file.
-/

noncomputable section

namespace Kakeya.Assouad

/-- Scalar data chosen before the runtime source and public scale.  The
internal sticky radius is fixed from the public target scale by the existing
outer-scale schedule. -/
structure PureWZ2HierarchyReentrantOrdinaryOwnerSchedule
    (capability : PureWZ2PropStickyCapability)
    (sigma outputLoss sourceLossCeiling : ℝ) where
  stickyLoss : ℝ
  stickyLoss_pos : 0 < stickyLoss
  stickyLoss_lt_output : stickyLoss < outputLoss
  kernel : PureWZ2PropStickyReentryKernelScheduleData
    (sigma := sigma) (outputLoss := stickyLoss)
    capability.normalizationExponent capability.logExponent
  structuralBudget : ℝ
  structuralBudget_le_half : structuralBudget ≤ outputLoss / 2
  traceSchedule : PureWZ2ReentryTraceFloorSchedule
    sigma outputLoss structuralBudget
  scalarClosure :
    PureWZ2HierarchyReentrantOrdinaryScalarClosure traceSchedule
  finalStructuralBudget : ℝ
  finalStructuralBudget_pos : 0 < finalStructuralBudget
  finalStructuralBudget_le_grain :
    finalStructuralBudget ≤ scalarClosure.grainLoss
  finalFloorSchedule : PureWZ2ReentryTraceFloorSchedule
    sigma scalarClosure.grainLoss finalStructuralBudget
  richLoss : ℝ := finalFloorSchedule.densityLoss / 4
  richLoss_eq : richLoss = finalFloorSchedule.densityLoss / 4
  richLoss_pos : 0 < richLoss
  richLoss_lt_one : richLoss < 1
  richLoss_half_lt_sigma : richLoss / 2 < sigma
  richLoss_le_grain : richLoss ≤ scalarClosure.grainLoss
  richLoss_half_lt_finalDensity :
    richLoss / 2 < finalFloorSchedule.densityLoss
  projection : PureWZ2SourceHorizontalProjectionThreshold sigma richLoss
  analytic : PureWZ2SourceFixedBinCoarseAnalyticThreshold
    projection.theoremEta
  jointVolumeLoss : ℝ := analytic.base.budget.volumeLoss
  jointVolumeLoss_eq : jointVolumeLoss = analytic.base.budget.volumeLoss
  jointVolumeLoss_pos : 0 < jointVolumeLoss
  sourceLossCeiling_pos : 0 < sourceLossCeiling
  sourceLossCeiling_output : sourceLossCeiling ≤ outputLoss / 100
  sourceLossCeiling_kernel : sourceLossCeiling ≤ kernel.sourceLoss
  sourceLossCeiling_scalar :
    sourceLossCeiling ≤ scalarClosure.sourceLossCeiling
  sourceLossCeiling_finalDensity :
    sourceLossCeiling ≤ finalFloorSchedule.densityLoss
  sourceLossCeiling_finalTrace :
    sourceLossCeiling ≤ finalFloorSchedule.traceSourceCeiling
  outerDelta₀ : ℝ
  outerDelta₀_pos : 0 < outerDelta₀
  outerDelta₀_le_one : outerDelta₀ ≤ 1
  outerScale :
    ∀ delta : ℝ, 0 < delta → delta ≤ outerDelta₀ →
      ∀ rho : ℝ,
        Real.rpow delta (1 - outputLoss) ≤ rho →
        rho ≤ Real.rpow delta outputLoss →
          Nonempty (PureWZ2SourceHorizontalFlexibleOuterScaleData
            delta rho stickyLoss outputLoss)
  delta₀ : ℝ
  delta₀_pos : 0 < delta₀
  delta₀_le_one : delta₀ ≤ 1
  delta₀_kernel : delta₀ ≤ kernel.delta₀
  delta₀_outer : delta₀ ≤ outerDelta₀
  delta₀_scalar : delta₀ ≤ scalarClosure.delta₀
  delta₀_finalFloor : delta₀ ≤ finalFloorSchedule.delta₀

/-- Construct the available pre-runtime schedule.  The sticky loss, kernel
schedule, trace-floor schedule, outer-scale threshold, source-loss ceiling,
and common delta threshold are all chosen here, before `current` and `rho`. -/
theorem PureWZ2PropStickyCapability.reentrantOrdinaryOwnerSchedule
    (capability : PureWZ2PropStickyCapability)
    {sigma outputLoss : ℝ}
    (critical : PureWZ2CriticalPackage sigma)
    (_hsigma : 0 < sigma) (_hsigmaOne : sigma < 1)
    (houtput : 0 < outputLoss) :
    Nonempty (Sigma fun sourceLossCeiling =>
      PureWZ2HierarchyReentrantOrdinaryOwnerSchedule capability sigma
        outputLoss sourceLossCeiling) := by
  let stickyLoss := min (outputLoss / 2) (1 / 2)
  have hsticky : 0 < stickyLoss := by
    dsimp only [stickyLoss]
    exact lt_min (div_pos houtput (by norm_num)) (by norm_num)
  have hstickyOutput : stickyLoss < outputLoss := by
    dsimp only [stickyLoss]
    exact (min_le_left _ _).trans_lt (by linarith)
  have hstickyOne : stickyLoss ≤ 1 := by
    exact (min_le_right _ _).trans (by norm_num)
  rcases capability.kernel sigma critical stickyLoss hsticky hstickyOne with
    ⟨kernel⟩
  let structuralBudget := outputLoss / 2
  have hstructuralBudget : 0 < structuralBudget := by
    dsimp only [structuralBudget]
    positivity
  have hstructuralOutput : structuralBudget ≤ outputLoss := by
    dsimp only [structuralBudget]
    linarith
  rcases critical.reentryTraceFloorSchedule houtput hstructuralBudget
      hstructuralOutput with ⟨traceSchedule⟩
  rcases pureWZ2_reentrantOrdinary_scalarClosure traceSchedule le_rfl with
    ⟨scalarClosure⟩
  have hgrainLoss : 0 < scalarClosure.grainLoss := by
    rw [scalarClosure.grainLoss_eq]
    exact div_pos traceSchedule.densityLoss_pos (by norm_num)
  let finalStructuralBudget := min (scalarClosure.grainLoss / 2) (sigma / 2)
  have hfinalStructuralBudget : 0 < finalStructuralBudget := by
    dsimp only [finalStructuralBudget]
    exact lt_min (div_pos hgrainLoss (by norm_num))
      (div_pos _hsigma (by norm_num))
  have hfinalStructuralGrain :
      finalStructuralBudget ≤ scalarClosure.grainLoss := by
    exact (min_le_left _ _).trans (by linarith)
  rcases critical.reentryTraceFloorSchedule hgrainLoss
      hfinalStructuralBudget hfinalStructuralGrain with
    ⟨finalFloorSchedule⟩
  let richLoss := finalFloorSchedule.densityLoss / 4
  have hrichLoss : 0 < richLoss := by
    dsimp only [richLoss]
    exact div_pos finalFloorSchedule.densityLoss_pos (by norm_num)
  have hrichGrain : richLoss ≤ scalarClosure.grainLoss := by
    dsimp only [richLoss]
    exact (div_le_self finalFloorSchedule.densityLoss_pos.le
      (by norm_num)).trans finalFloorSchedule.densityLoss_le_floor
  have hrichHalfDensity :
      richLoss / 2 < finalFloorSchedule.densityLoss := by
    dsimp only [richLoss]
    linarith [finalFloorSchedule.densityLoss_pos]
  have hrichSigma : richLoss < sigma := by
    have hfinalStructuralSigma : finalStructuralBudget ≤ sigma / 2 :=
      min_le_right _ _
    have hcritical :
        finalFloorSchedule.criticalFloor.structuralLoss ≤
          finalStructuralBudget :=
      finalFloorSchedule.criticalFloor.structuralLoss_le
    have hdensity : finalFloorSchedule.densityLoss ≤
        finalStructuralBudget / 4 := by
      rw [finalFloorSchedule.densityLoss_eq]
      linarith
    dsimp only [richLoss]
    linarith
  have hrichOne : richLoss < 1 := hrichSigma.trans _hsigmaOne
  have hrichHalfSigma : richLoss / 2 < sigma := by
    linarith [hrichLoss, hrichSigma]
  rcases pureWZ2_sourceHorizontal_projection_threshold _hsigma hrichLoss
      hrichOne hrichHalfSigma with ⟨projection⟩
  rcases pureWZ2_sourceFixedBinCoarse_analytic_threshold
      projection.theoremEta_pos with ⟨analytic⟩
  let jointVolumeLoss := analytic.base.budget.volumeLoss
  have hjointVolumeLoss : 0 < jointVolumeLoss := by
    exact analytic.base.budget.volumeLoss_pos
  rcases pureWZ2_sourceHorizontal_outerScale_flexible_schedule hsticky
      hstickyOutput with ⟨outerDelta₀, houterDelta₀, houterDelta₀One, outerScale⟩
  let sourceLossCeiling := min (outputLoss / 100)
    (min kernel.sourceLoss
      (min scalarClosure.sourceLossCeiling
        (min finalFloorSchedule.densityLoss
          finalFloorSchedule.traceSourceCeiling)))
  have hsourceLossCeiling : 0 < sourceLossCeiling := by
    dsimp only [sourceLossCeiling]
    exact lt_min (div_pos houtput (by norm_num))
      (lt_min kernel.sourceLoss_pos
        (lt_min scalarClosure.sourceLossCeiling_pos
          (lt_min finalFloorSchedule.densityLoss_pos
            finalFloorSchedule.traceSourceCeiling_pos)))
  let delta₀ := min kernel.delta₀
    (min outerDelta₀ (min scalarClosure.delta₀ finalFloorSchedule.delta₀))
  have hdelta₀ : 0 < delta₀ := by
    dsimp only [delta₀]
    exact lt_min kernel.delta₀_pos
      (lt_min houterDelta₀
        (lt_min scalarClosure.delta₀_pos finalFloorSchedule.delta₀_pos))
  exact ⟨⟨sourceLossCeiling, {
    stickyLoss := stickyLoss
    stickyLoss_pos := hsticky
    stickyLoss_lt_output := hstickyOutput
    kernel := kernel
    structuralBudget := structuralBudget
    structuralBudget_le_half := le_rfl
    traceSchedule := traceSchedule
    scalarClosure := scalarClosure
    finalStructuralBudget := finalStructuralBudget
    finalStructuralBudget_pos := hfinalStructuralBudget
    finalStructuralBudget_le_grain := hfinalStructuralGrain
    finalFloorSchedule := finalFloorSchedule
    richLoss := richLoss
    richLoss_eq := rfl
    richLoss_pos := hrichLoss
    richLoss_lt_one := hrichOne
    richLoss_half_lt_sigma := hrichHalfSigma
    richLoss_le_grain := hrichGrain
    richLoss_half_lt_finalDensity := hrichHalfDensity
    projection := projection
    analytic := analytic
    jointVolumeLoss := jointVolumeLoss
    jointVolumeLoss_eq := rfl
    jointVolumeLoss_pos := hjointVolumeLoss
    sourceLossCeiling_pos := hsourceLossCeiling
    sourceLossCeiling_output := min_le_left _ _
    sourceLossCeiling_kernel :=
      (min_le_right _ _).trans (min_le_left _ _)
    sourceLossCeiling_scalar :=
      (min_le_right _ _).trans <|
        (min_le_right _ _).trans (min_le_left _ _)
    sourceLossCeiling_finalDensity :=
      (min_le_right _ _).trans <|
        (min_le_right _ _).trans <|
          (min_le_right _ _).trans (min_le_left _ _)
    sourceLossCeiling_finalTrace :=
      (min_le_right _ _).trans <|
        (min_le_right _ _).trans <|
          (min_le_right _ _).trans (min_le_right _ _)
    outerDelta₀ := outerDelta₀
    outerDelta₀_pos := houterDelta₀
    outerDelta₀_le_one := houterDelta₀One
    outerScale := outerScale
    delta₀ := delta₀
    delta₀_pos := hdelta₀
    delta₀_le_one := (min_le_left _ _).trans kernel.delta₀_le_one
    delta₀_kernel := min_le_left _ _
    delta₀_outer := (min_le_right _ _).trans (min_le_left _ _)
    delta₀_scalar := (min_le_right _ _).trans <|
      (min_le_right _ _).trans (min_le_left _ _)
    delta₀_finalFloor := (min_le_right _ _).trans <|
      (min_le_right _ _).trans (min_le_right _ _)
  }⟩⟩

/-- The exact first kernel output on the runtime re-entry and internal sticky
scale.  It is constructed by `capability.kernel`; no family is reselected. -/
structure PureWZ2HierarchyReentrantOrdinaryKernelOutput
    {sigma inputLoss delta outputLoss sourceLossCeiling targetRho : ℝ}
    {capability : PureWZ2PropStickyCapability}
    {current : PureWZ2ReentrantGrainSource sigma inputLoss delta
      capability.normalizationExponent}
    (schedule : PureWZ2HierarchyReentrantOrdinaryOwnerSchedule capability
      sigma outputLoss sourceLossCeiling)
    (outer : PureWZ2SourceHorizontalFlexibleOuterScaleData
      delta targetRho schedule.stickyLoss outputLoss) where
  requested : WZ2PaperRequestedScale delta
  requested_val : requested.1 =
    pureWZ2SourceHorizontalInternalScale targetRho
  firstSeedLogExponent : ℕ
  firstReentrant : PureWZ2ReentrantPropStickyData
    (sigma := sigma) (outputLoss := schedule.stickyLoss)
    current.grain.shading requested capability.normalizationExponent
      firstSeedLogExponent

namespace PureWZ2HierarchyReentrantOrdinaryKernelOutput

/-- Compatibility projection to the first sticky datum.  It is definitionally
the datum carried by the same `runReentrant` witness, not a separately
selected output of the weaker kernel entry point. -/
abbrev first
    {sigma inputLoss delta outputLoss sourceLossCeiling targetRho : ℝ}
    {capability : PureWZ2PropStickyCapability}
    {current : PureWZ2ReentrantGrainSource sigma inputLoss delta
      capability.normalizationExponent}
    {schedule : PureWZ2HierarchyReentrantOrdinaryOwnerSchedule capability
      sigma outputLoss sourceLossCeiling}
    {outer : PureWZ2SourceHorizontalFlexibleOuterScaleData
      delta targetRho schedule.stickyLoss outputLoss}
    (kernelOutput : PureWZ2HierarchyReentrantOrdinaryKernelOutput
      (current := current) schedule outer) :
    PureWZ2PropStickyData
      (sigma := sigma) (outputLoss := schedule.stickyLoss)
      current.grain.shading kernelOutput.requested
        kernelOutput.firstSeedLogExponent :=
  kernelOutput.firstReentrant.data

/-- The canonical square-root scale requested by the second owner call. -/
noncomputable def sqrtRequested
    {sigma inputLoss delta outputLoss sourceLossCeiling targetRho : ℝ}
    {capability : PureWZ2PropStickyCapability}
    {current : PureWZ2ReentrantGrainSource sigma inputLoss delta
      capability.normalizationExponent}
    {schedule : PureWZ2HierarchyReentrantOrdinaryOwnerSchedule capability
      sigma outputLoss sourceLossCeiling}
    {outer : PureWZ2SourceHorizontalFlexibleOuterScaleData
      delta targetRho schedule.stickyLoss outputLoss}
    (kernelOutput : PureWZ2HierarchyReentrantOrdinaryKernelOutput
      (current := current) schedule outer) :
    WZ2PaperRequestedScale kernelOutput.requested.1 := by
  refine ⟨Real.sqrt kernelOutput.requested.1, ?_, ?_⟩
  · have hpos : 0 < kernelOutput.requested.1 :=
      kernelOutput.first.coarse_extremal.delta_pos
    nlinarith [Real.sqrt_nonneg kernelOutput.requested.1,
      Real.sq_sqrt hpos.le, kernelOutput.requested.property.2]
  · exact Real.sqrt_le_one.mpr kernelOutput.requested.property.2

@[simp] theorem sqrtRequested_val
    {sigma inputLoss delta outputLoss sourceLossCeiling targetRho : ℝ}
    {capability : PureWZ2PropStickyCapability}
    {current : PureWZ2ReentrantGrainSource sigma inputLoss delta
      capability.normalizationExponent}
    {schedule : PureWZ2HierarchyReentrantOrdinaryOwnerSchedule capability
      sigma outputLoss sourceLossCeiling}
    {outer : PureWZ2SourceHorizontalFlexibleOuterScaleData
      delta targetRho schedule.stickyLoss outputLoss}
    (kernelOutput : PureWZ2HierarchyReentrantOrdinaryKernelOutput
      (current := current) schedule outer) :
    kernelOutput.sqrtRequested.1 = Real.sqrt kernelOutput.requested.1 := rfl

end PureWZ2HierarchyReentrantOrdinaryKernelOutput

/-- Execute the reentrant kernel on the exact current source and retain the
complete first witness. -/
theorem PureWZ2HierarchyReentrantOrdinaryOwnerSchedule.kernelOutput_nonempty
    {sigma inputLoss delta outputLoss sourceLossCeiling targetRho : ℝ}
    {capability : PureWZ2PropStickyCapability}
    {current : PureWZ2ReentrantGrainSource sigma inputLoss delta
      capability.normalizationExponent}
    (schedule : PureWZ2HierarchyReentrantOrdinaryOwnerSchedule capability
      sigma outputLoss sourceLossCeiling)
    (hinputCeiling : inputLoss ≤ sourceLossCeiling)
    (hdelta : 0 < delta) (hdeltaSmall : delta ≤ schedule.delta₀)
    (outer : PureWZ2SourceHorizontalFlexibleOuterScaleData
      delta targetRho schedule.stickyLoss outputLoss) :
    Nonempty (PureWZ2HierarchyReentrantOrdinaryKernelOutput
      (current := current) schedule outer) := by
  let requested : WZ2PaperRequestedScale delta :=
    ⟨pureWZ2SourceHorizontalInternalScale targetRho,
      outer.delta_le_internal, outer.internal_le_one⟩
  have ordinaryLoss_le_kernel :
      current.ordinaryLoss ≤ schedule.kernel.sourceLoss := by
    exact current.reentry.sourceLoss_le_half.trans
      ((div_le_self current.reentry.normalizationLoss_pos.le
        (by norm_num)).trans
          (le_trans (by linarith)
            (hinputCeiling.trans schedule.sourceLossCeiling_kernel)))
  have inputLoss_le_kernel :
      inputLoss ≤ schedule.kernel.normalizationLoss := by
    exact (hinputCeiling.trans schedule.sourceLossCeiling_kernel).trans
      (schedule.kernel.sourceLoss_le_half.trans
        (div_le_self schedule.kernel.normalizationLoss_pos.le
          (by norm_num)))
  let kernelReentry : PureWZ2PropStickyReentryData
      (sigma := sigma) current.grain.shading capability.normalizationExponent
      schedule.kernel.sourceLoss schedule.kernel.normalizationLoss :=
    current.reentry.mono_losses ordinaryLoss_le_kernel inputLoss_le_kernel
      schedule.kernel.sourceLoss_pos schedule.kernel.normalizationLoss_pos
      schedule.kernel.sourceLoss_le_half
  rcases schedule.kernel.runReentrant delta hdelta
      (hdeltaSmall.trans schedule.delta₀_kernel) current.grain.family
      current.grain.shading kernelReentry
      current.ordinary_axial_window_eighth requested outer.sticky_lower
      outer.sticky_upper with ⟨firstReentrant⟩
  exact
    ⟨{ requested := requested
       requested_val := rfl
       firstSeedLogExponent := capability.logExponent
       firstReentrant := firstReentrant }⟩

/-- The narrow actual-owner leaf left after the public kernel has run.  It
upgrades that exact kernel output to two exact Node-5 owner calls through the
actual intermediate grain refinement, and supplies the ordinary all-bin
geometry on precisely that wiring. -/
structure PureWZ2HierarchyReentrantOrdinaryActualOwnerReceipt
    {sigma inputLoss delta outputLoss sourceLossCeiling targetRho : ℝ}
    {capability : PureWZ2PropStickyCapability}
    {current : PureWZ2ReentrantGrainSource sigma inputLoss delta
      capability.normalizationExponent}
    {schedule : PureWZ2HierarchyReentrantOrdinaryOwnerSchedule capability
      sigma outputLoss sourceLossCeiling}
    {outer : PureWZ2SourceHorizontalFlexibleOuterScaleData
      delta targetRho schedule.stickyLoss outputLoss}
    (kernelOutput : PureWZ2HierarchyReentrantOrdinaryKernelOutput
      (current := current) schedule outer) where
  middleLoss : ℝ
  firstExact : PureWZ2Node05ExactMultiplicityPostRefinementData
    (sigma := sigma) (seedLoss := schedule.stickyLoss)
    (outputLoss := schedule.stickyLoss) current.grain.shading
    kernelOutput.requested capability.normalizationExponent
    kernelOutput.firstSeedLogExponent capability.logExponent
  first_data_eq : firstExact.seed.data = kernelOutput.first
  grainSchedule : PureWZ2Node05SameExtremizerSchedule sigma middleLoss
  coarse_slope_eq : ∀ coarseGrains : PureWZ2GrainRefinementData
      firstExact.toNode5StickyData.croppedCoarseShading sigma middleLoss,
    coarseGrains.globalGrains.slope = current.grain.globalGrains.slope
  firstLoss_le_input : schedule.stickyLoss ≤ grainSchedule.inputLoss
  rho_le_grain_schedule :
    kernelOutput.requested.1 ≤ grainSchedule.delta₀
  sqrtRequested : WZ2PaperRequestedScale kernelOutput.requested.1
  sqrtRequested_eq : sqrtRequested.1 =
    Real.sqrt (pureWZ2SourceHorizontalInternalScale targetRho)
  fineSeedLoss : ℝ
  secondSeedLogExponent : ℕ
  continuation :
    ∀ coarseGrains : PureWZ2GrainRefinementData
        firstExact.toNode5StickyData.croppedCoarseShading sigma middleLoss,
      PureWZ2Node05SecondOwnerContinuation
        (rhoRequested := kernelOutput.requested)
        (fineSeedLoss := fineSeedLoss) (secondLoss := schedule.stickyLoss)
        (reentryNormalizationExponent := capability.normalizationExponent)
        (secondLogExponent := secondSeedLogExponent)
        (commonLogExponent := capability.logExponent)
        firstExact.toNode5StickyData coarseGrains sqrtRequested

/-- The exact mathematical output required from the two owner calls by the
ordinary Lemma-24 geometry.  Upstream construction provenance may come either
from the legacy exact-truncation route or from the synchronized-overlay route;
the downstream carrier construction needs only this common two-scale object. -/
structure PureWZ2HierarchyReentrantOrdinaryOwnerOutputReceipt
    {sigma inputLoss delta outputLoss sourceLossCeiling targetRho : ℝ}
    {capability : PureWZ2PropStickyCapability}
    {current : PureWZ2ReentrantGrainSource sigma inputLoss delta
      capability.normalizationExponent}
    {schedule : PureWZ2HierarchyReentrantOrdinaryOwnerSchedule capability
      sigma outputLoss sourceLossCeiling}
    {outer : PureWZ2SourceHorizontalFlexibleOuterScaleData
      delta targetRho schedule.stickyLoss outputLoss}
    (kernelOutput : PureWZ2HierarchyReentrantOrdinaryKernelOutput
      (current := current) schedule outer) where
  middleLoss : ℝ
  twoScale : PureWZ2OneScaleTwoScaleStickyData current.grain
    (pureWZ2SourceHorizontalInternalScale targetRho) middleLoss
    schedule.stickyLoss capability.logExponent
  first_data_eq : HEq twoScale.coarse.seed.data kernelOutput.first

namespace PureWZ2Node05SynchronizedTwoCallStage

/-- Forget the synchronized construction details only after its first seed has
been identified with the public kernel output.  The radius equality stored by
the stage transports the resulting two-scale object to the hierarchy's
canonical internal radius; no family, shading, or owner call is reselected. -/
noncomputable def toHierarchyReentrantOrdinaryOwnerOutputReceipt
    {sigma inputLoss delta outputLoss sourceLossCeiling targetRho ambientLoss
      sourceLoss normalizationLoss grainLoss outputEta selectedLoss seedLoss : ℝ}
    {capability : PureWZ2PropStickyCapability}
    {current : PureWZ2ReentrantGrainSource sigma inputLoss delta
      capability.normalizationExponent}
    {schedule : PureWZ2HierarchyReentrantOrdinaryOwnerSchedule capability
      sigma outputLoss sourceLossCeiling}
    {outer : PureWZ2SourceHorizontalFlexibleOuterScaleData
      delta targetRho schedule.stickyLoss outputLoss}
    {kernelOutput : PureWZ2HierarchyReentrantOrdinaryKernelOutput
      (current := current) schedule outer}
    {ambientLogExponent ancestorNormalizationExponent
      selectedNormalizationExponent secondSeedLogExponent : ℕ}
    {ambient : PureWZ2Node5StickyData
      (sigma := sigma) (outputLoss := ambientLoss) current.grain.shading
      kernelOutput.requested ambientLogExponent}
    {ancestor : PureWZ2PropStickyReentryData
      (sigma := sigma) ambient.croppedCoarseShading
      ancestorNormalizationExponent sourceLoss normalizationLoss}
    {coarseGrains : PureWZ2GrainRefinementData
      ambient.croppedCoarseShading sigma grainLoss}
    {croppedMassFraction : ENNReal}
    {selection : PureWZ2Node05SynchronizedOwnerSelection
      (outputEta := outputEta) (selectedLoss := selectedLoss)
      (selectedNormalizationExponent := selectedNormalizationExponent)
      ambient ancestor coarseGrains croppedMassFraction}
    {sqrtRequested : WZ2PaperRequestedScale kernelOutput.requested.1}
    (stage : PureWZ2Node05SynchronizedTwoCallStage
      (seedLoss := seedLoss) (outputLoss := schedule.stickyLoss)
      (firstLogExponent := capability.logExponent)
      (secondSeedLogExponent := secondSeedLogExponent)
      current.grain ambient ancestor coarseGrains croppedMassFraction
      selection sqrtRequested)
    (first_data_eq : HEq ambient.seed.data kernelOutput.first) :
    PureWZ2HierarchyReentrantOrdinaryOwnerOutputReceipt
      (current := current) kernelOutput := by
  have rho_eq : stage.rho =
      pureWZ2SourceHorizontalInternalScale targetRho :=
    stage.rho_eq.symm.trans kernelOutput.requested_val
  let twoScale : PureWZ2OneScaleTwoScaleStickyData current.grain
      (pureWZ2SourceHorizontalInternalScale targetRho) selectedLoss
      schedule.stickyLoss capability.logExponent := {
    coarseLoss := selectedLoss
    rhoRequested := kernelOutput.requested
    rhoRequested_eq := kernelOutput.requested_val
    coarse := stage.firstReceipt.toNode5StickyData
    coarseGrains := selection.receipt.toIdentityGrainRefinementData
    coarse_slope_eq := by
      change coarseGrains.globalGrains.slope = current.grain.globalGrains.slope
      exact stage.coarse_slope_eq
    sqrtRequested := sqrtRequested
    sqrtRequested_eq := stage.sqrt_eq.trans (congrArg Real.sqrt rho_eq)
    fine := stage.second.output.toNode5StickyData
  }
  exact {
    middleLoss := selectedLoss
    twoScale := twoScale
    first_data_eq := by
      change HEq ambient.seed.data kernelOutput.first
      exact first_data_eq
  }

end PureWZ2Node05SynchronizedTwoCallStage

namespace PureWZ2HierarchyReentrantOrdinaryActualOwnerReceipt

/-- Assemble the exact two-call wiring furnished by the actual-owner receipt. -/
theorem ownerTwoCall_nonempty
    {sigma inputLoss delta outputLoss sourceLossCeiling targetRho : ℝ}
    {capability : PureWZ2PropStickyCapability}
    {current : PureWZ2ReentrantGrainSource sigma inputLoss delta
      capability.normalizationExponent}
    {schedule : PureWZ2HierarchyReentrantOrdinaryOwnerSchedule capability
      sigma outputLoss sourceLossCeiling}
    {outer : PureWZ2SourceHorizontalFlexibleOuterScaleData
      delta targetRho schedule.stickyLoss outputLoss}
    {kernelOutput : PureWZ2HierarchyReentrantOrdinaryKernelOutput
      (current := current) schedule outer}
    (receipt : PureWZ2HierarchyReentrantOrdinaryActualOwnerReceipt
      (current := current) kernelOutput) :
    Nonempty (PureWZ2Node05TwoCallExactMultiplicityWiring current.grain
      (pureWZ2SourceHorizontalInternalScale targetRho) receipt.middleLoss
      schedule.stickyLoss capability.logExponent) := by
  apply pureWZ2Node05_twoCallOfFirstExact
    schedule.stickyLoss capability.normalizationExponent
    kernelOutput.firstSeedLogExponent kernelOutput.requested
    kernelOutput.requested_val
    receipt.firstExact receipt.grainSchedule receipt.coarse_slope_eq
    receipt.firstLoss_le_input
    receipt.rho_le_grain_schedule receipt.sqrtRequested
    receipt.sqrtRequested_eq receipt.fineSeedLoss
    capability.normalizationExponent receipt.secondSeedLogExponent
    receipt.continuation

/-- Forget the construction-specific exact wrappers only after both calls have
been assembled.  The resulting two-scale value still carries the literal
source, intermediate grain refinement, and second call as dependent fields. -/
noncomputable def toOwnerOutput
    {sigma inputLoss delta outputLoss sourceLossCeiling targetRho : ℝ}
    {capability : PureWZ2PropStickyCapability}
    {current : PureWZ2ReentrantGrainSource sigma inputLoss delta
      capability.normalizationExponent}
    {schedule : PureWZ2HierarchyReentrantOrdinaryOwnerSchedule capability
      sigma outputLoss sourceLossCeiling}
    {outer : PureWZ2SourceHorizontalFlexibleOuterScaleData
      delta targetRho schedule.stickyLoss outputLoss}
    {kernelOutput : PureWZ2HierarchyReentrantOrdinaryKernelOutput
      (current := current) schedule outer}
    (receipt : PureWZ2HierarchyReentrantOrdinaryActualOwnerReceipt
      (current := current) kernelOutput) :
    PureWZ2HierarchyReentrantOrdinaryOwnerOutputReceipt
      (current := current) kernelOutput := by
  let coarseGrains := Classical.choice <|
    pureWZ2Node05Owner_intermediateGrains
      receipt.firstExact.toNode5StickyData receipt.grainSchedule
      receipt.firstLoss_le_input receipt.rho_le_grain_schedule
  let next := receipt.continuation coarseGrains
  let twoScale : PureWZ2OneScaleTwoScaleStickyData current.grain
      (pureWZ2SourceHorizontalInternalScale targetRho) receipt.middleLoss
      schedule.stickyLoss capability.logExponent := {
    coarseLoss := schedule.stickyLoss
    rhoRequested := kernelOutput.requested
    rhoRequested_eq := kernelOutput.requested_val
    coarse := receipt.firstExact.toNode5StickyData
    coarseGrains := coarseGrains
    coarse_slope_eq := receipt.coarse_slope_eq coarseGrains
    sqrtRequested := receipt.sqrtRequested
    sqrtRequested_eq := receipt.sqrtRequested_eq
    fine := next.call.output.toNode5StickyData
  }
  exact {
    middleLoss := receipt.middleLoss
    twoScale := twoScale
    first_data_eq := by
      change HEq receipt.firstExact.seed.data kernelOutput.first
      exact heq_of_eq receipt.first_data_eq
  }

/-- The deterministic projection is, in particular, inhabited. -/
theorem ownerOutput_nonempty
    {sigma inputLoss delta outputLoss sourceLossCeiling targetRho : ℝ}
    {capability : PureWZ2PropStickyCapability}
    {current : PureWZ2ReentrantGrainSource sigma inputLoss delta
      capability.normalizationExponent}
    {schedule : PureWZ2HierarchyReentrantOrdinaryOwnerSchedule capability
      sigma outputLoss sourceLossCeiling}
    {outer : PureWZ2SourceHorizontalFlexibleOuterScaleData
      delta targetRho schedule.stickyLoss outputLoss}
    {kernelOutput : PureWZ2HierarchyReentrantOrdinaryKernelOutput
      (current := current) schedule outer}
    (receipt : PureWZ2HierarchyReentrantOrdinaryActualOwnerReceipt
      (current := current) kernelOutput) :
    Nonempty (PureWZ2HierarchyReentrantOrdinaryOwnerOutputReceipt
      (current := current) kernelOutput) :=
  ⟨receipt.toOwnerOutput⟩

@[simp] theorem toOwnerOutput_middleLoss
    {sigma inputLoss delta outputLoss sourceLossCeiling targetRho : ℝ}
    {capability : PureWZ2PropStickyCapability}
    {current : PureWZ2ReentrantGrainSource sigma inputLoss delta
      capability.normalizationExponent}
    {schedule : PureWZ2HierarchyReentrantOrdinaryOwnerSchedule capability
      sigma outputLoss sourceLossCeiling}
    {outer : PureWZ2SourceHorizontalFlexibleOuterScaleData
      delta targetRho schedule.stickyLoss outputLoss}
    {kernelOutput : PureWZ2HierarchyReentrantOrdinaryKernelOutput
      (current := current) schedule outer}
    (receipt : PureWZ2HierarchyReentrantOrdinaryActualOwnerReceipt
      (current := current) kernelOutput) :
    receipt.toOwnerOutput.middleLoss = receipt.middleLoss := rfl

/-- Forget only the actual-owner construction details after assembling their
exact two-call output. -/
theorem nonCWAInputs_nonempty
    {sigma inputLoss delta outputLoss sourceLossCeiling targetRho : ℝ}
    {capability : PureWZ2PropStickyCapability}
    {current : PureWZ2ReentrantGrainSource sigma inputLoss delta
      capability.normalizationExponent}
    {schedule : PureWZ2HierarchyReentrantOrdinaryOwnerSchedule capability
      sigma outputLoss sourceLossCeiling}
    {outer : PureWZ2SourceHorizontalFlexibleOuterScaleData
      delta targetRho schedule.stickyLoss outputLoss}
    {kernelOutput : PureWZ2HierarchyReentrantOrdinaryKernelOutput
      (current := current) schedule outer}
    (receipt : PureWZ2HierarchyReentrantOrdinaryActualOwnerReceipt
      (current := current) kernelOutput)
    (ordinaryAllBins :
      ∀ ownerTwoCall : PureWZ2Node05TwoCallExactMultiplicityWiring
          current.grain (pureWZ2SourceHorizontalInternalScale targetRho)
          receipt.middleLoss schedule.stickyLoss capability.logExponent,
        let twoScale := ownerTwoCall.toOneScaleTwoScaleStickyData
        ∀ pullback : PureWZ2TwoScaleCellPullbackData twoScale,
          ∀ _prepared : PureWZ2SourceCarrierPreparation pullback,
            Nonempty (PureWZ2LocallyLinearOneScaleData current.grain
              schedule.scalarClosure.grainLoss targetRho)) :
    Nonempty (PureWZ2HierarchyReentrantOrdinaryNonCWAInputs
      (grainLoss := schedule.scalarClosure.grainLoss)
      (stickyRho := pureWZ2SourceHorizontalInternalScale targetRho)
      (logExponent := capability.logExponent) current receipt.middleLoss
      schedule.stickyLoss) := by
  rcases receipt.ownerTwoCall_nonempty with ⟨ownerTwoCall⟩
  exact ⟨{
    twoScale := ownerTwoCall.toOneScaleTwoScaleStickyData
    ordinaryAllBins := by
      intro pullback prepared
      have output := ordinaryAllBins ownerTwoCall pullback prepared
      simpa [outer.final_scale_eq] using output
  }⟩

end PureWZ2HierarchyReentrantOrdinaryActualOwnerReceipt

/-- Original-slope AD on source slabs at the exact first-sticky radius.  The
receipt is indexed by the common two-scale owner output, so neither its source
nor its scale can be replaced by an independently selected witness. -/
structure PureWZ2HierarchyReentrantOrdinarySourceRhoSlabADReceipt
    {sigma inputLoss delta outputLoss sourceLossCeiling targetRho : ℝ}
    {capability : PureWZ2PropStickyCapability}
    {current : PureWZ2ReentrantGrainSource sigma inputLoss delta
      capability.normalizationExponent}
    {schedule : PureWZ2HierarchyReentrantOrdinaryOwnerSchedule capability
      sigma outputLoss sourceLossCeiling}
    {outer : PureWZ2SourceHorizontalFlexibleOuterScaleData
      delta targetRho schedule.stickyLoss outputLoss}
    {kernelOutput : PureWZ2HierarchyReentrantOrdinaryKernelOutput
      (current := current) schedule outer}
    (ownerOutput : PureWZ2HierarchyReentrantOrdinaryOwnerOutputReceipt
      (current := current) kernelOutput) where
  constant : ENNReal
  sourceRhoSlabAD : ∀ z ∈ Set.Icc (-1 : ℝ) 1,
    IsADSet1
      (globalGrainProjection current.grain.globalGrains.slope
        (globalGrainSlab current.grain.shading.union z
          (pureWZ2SourceHorizontalInternalScale targetRho)))
      (pureWZ2SourceHorizontalInternalScale targetRho) (1 - sigma) constant
  constant_absorb :
    144 * constant ≤
      10 * Kakeya.realRpowENN
        (pureWZ2SourceHorizontalInternalScale targetRho)
          (-ownerOutput.middleLoss)

namespace PureWZ2HierarchyReentrantOrdinarySourceRhoSlabADReceipt

/-- Package the inherited source-slab invariant at the exact internal sticky
radius and owner loss. -/
noncomputable def ofSourceRhoSlabADAt
    {sigma inputLoss delta outputLoss sourceLossCeiling targetRho : ℝ}
    {capability : PureWZ2PropStickyCapability}
    {current : PureWZ2ReentrantGrainSource sigma inputLoss delta
      capability.normalizationExponent}
    {schedule : PureWZ2HierarchyReentrantOrdinaryOwnerSchedule capability
      sigma outputLoss sourceLossCeiling}
    {outer : PureWZ2SourceHorizontalFlexibleOuterScaleData
      delta targetRho schedule.stickyLoss outputLoss}
    {kernelOutput : PureWZ2HierarchyReentrantOrdinaryKernelOutput
      (current := current) schedule outer}
    (ownerOutput : PureWZ2HierarchyReentrantOrdinaryOwnerOutputReceipt
      (current := current) kernelOutput)
    (sourceSlab : PureWZ2SourceRhoSlabADAt current
      (pureWZ2SourceHorizontalInternalScale targetRho)
      ownerOutput.middleLoss) :
    PureWZ2HierarchyReentrantOrdinarySourceRhoSlabADReceipt
      ownerOutput := by
  let constant := Classical.choose sourceSlab
  have hsourceSlab := Classical.choose_spec sourceSlab
  exact {
    constant := constant
    sourceRhoSlabAD := hsourceSlab.1
    constant_absorb := hsourceSlab.2
  }

end PureWZ2HierarchyReentrantOrdinarySourceRhoSlabADReceipt

/-- Construction-neutral output of the paper-order post-owner step.

All common-bin, pre-bin height regularization, graph, Alternative-A, source
refill, and residue witnesses remain internal to the producer.  The hierarchy
consumes only the resulting one-scale datum on the literal current source. -/
structure PureWZ2HierarchyReentrantOrdinaryPostOwnerReceipt
    {sigma inputLoss delta outputLoss sourceLossCeiling targetRho : ℝ}
    {capability : PureWZ2PropStickyCapability}
    {current : PureWZ2ReentrantGrainSource sigma inputLoss delta
      capability.normalizationExponent}
    {schedule : PureWZ2HierarchyReentrantOrdinaryOwnerSchedule capability
      sigma outputLoss sourceLossCeiling}
    {outer : PureWZ2SourceHorizontalFlexibleOuterScaleData
      delta targetRho schedule.stickyLoss outputLoss}
    {kernelOutput : PureWZ2HierarchyReentrantOrdinaryKernelOutput
      (current := current) schedule outer}
    (ownerOutput : PureWZ2HierarchyReentrantOrdinaryOwnerOutputReceipt
      (current := current) kernelOutput)
    (pullback : PureWZ2TwoScaleCellPullbackData
      ownerOutput.twoScale)
    (_prepared : PureWZ2SourceCarrierPreparation pullback) where
  oneScale : PureWZ2LocallyLinearOneScaleData current.grain
    schedule.scalarClosure.grainLoss
    (pureWZ2SourceHorizontalFinalScale
      (pureWZ2SourceHorizontalInternalScale targetRho))

/-- Conditional completion of the honest post-owner boundary.  This is kept
separate so a caller cannot treat the existence of the two missing geometric
receipts as if the downstream paper-order assembly had already been proved. -/
structure PureWZ2HierarchyReentrantOrdinaryCompletedPostOwnerReceipt
    {sigma inputLoss delta outputLoss sourceLossCeiling targetRho : ℝ}
    {capability : PureWZ2PropStickyCapability}
    {current : PureWZ2ReentrantGrainSource sigma inputLoss delta
      capability.normalizationExponent}
    {schedule : PureWZ2HierarchyReentrantOrdinaryOwnerSchedule capability
      sigma outputLoss sourceLossCeiling}
    {outer : PureWZ2SourceHorizontalFlexibleOuterScaleData
      delta targetRho schedule.stickyLoss outputLoss}
    {kernelOutput : PureWZ2HierarchyReentrantOrdinaryKernelOutput
      (current := current) schedule outer}
    (ownerOutput : PureWZ2HierarchyReentrantOrdinaryOwnerOutputReceipt
      (current := current) kernelOutput)
    (pullback : PureWZ2TwoScaleCellPullbackData
      ownerOutput.twoScale)
    (prepared : PureWZ2SourceCarrierPreparation pullback) where
  oneScale : PureWZ2LocallyLinearOneScaleData current.grain
    schedule.scalarClosure.grainLoss
    (pureWZ2SourceHorizontalFinalScale
      (pureWZ2SourceHorizontalInternalScale targetRho))

namespace PureWZ2HierarchyReentrantOrdinaryCompletedPostOwnerReceipt

/-- Convert a producer indexed by the actual two-call/pullback/preparation
chain to the existing non-CWA front-end input.  The producer is invoked only
after the owner has chosen its two-call wiring, and again on each literal
pullback and preparation requested by the downstream consumer. -/
theorem toRuntimeNonCWAInputs_nonempty
    {sigma inputLoss delta outputLoss sourceLossCeiling targetRho : ℝ}
    {capability : PureWZ2PropStickyCapability}
    {current : PureWZ2ReentrantGrainSource sigma inputLoss delta
      capability.normalizationExponent}
    {schedule : PureWZ2HierarchyReentrantOrdinaryOwnerSchedule capability
      sigma outputLoss sourceLossCeiling}
    {outer : PureWZ2SourceHorizontalFlexibleOuterScaleData
      delta targetRho schedule.stickyLoss outputLoss}
    {kernelOutput : PureWZ2HierarchyReentrantOrdinaryKernelOutput
      (current := current) schedule outer}
    (ownerOutput : PureWZ2HierarchyReentrantOrdinaryOwnerOutputReceipt
      (current := current) kernelOutput)
    (postOwner :
      ∀ pullback : PureWZ2TwoScaleCellPullbackData ownerOutput.twoScale,
        ∀ prepared : PureWZ2SourceCarrierPreparation pullback,
          Nonempty (PureWZ2HierarchyReentrantOrdinaryCompletedPostOwnerReceipt
            ownerOutput pullback prepared))
    (hinputCeiling : inputLoss ≤ sourceLossCeiling)
    (hdeltaSmall : delta ≤ schedule.delta₀) :
    Nonempty (PureWZ2HierarchyReentrantOrdinaryRuntimeNonCWAInputs
      (rho := targetRho) current schedule.traceSchedule) := by
  let nonCWA : PureWZ2HierarchyReentrantOrdinaryNonCWAInputs
      (grainLoss := schedule.scalarClosure.grainLoss)
      (stickyRho := pureWZ2SourceHorizontalInternalScale targetRho)
      (logExponent := capability.logExponent) current ownerOutput.middleLoss
      schedule.stickyLoss := {
    twoScale := ownerOutput.twoScale
    ordinaryAllBins := by
      intro pullback prepared
      rcases postOwner pullback prepared with ⟨receipt⟩
      exact ⟨by simpa [outer.final_scale_eq] using
        receipt.oneScale⟩
  }
  have hinputScalar : inputLoss ≤
      schedule.scalarClosure.sourceLossCeiling :=
    hinputCeiling.trans schedule.sourceLossCeiling_scalar
  have hdeltaScalar : delta ≤ schedule.scalarClosure.delta₀ :=
    hdeltaSmall.trans schedule.delta₀_scalar
  let scalar := schedule.scalarClosure.runtime inputLoss
    current.reentry.normalizationLoss_pos hinputScalar delta
    current.grain.extremal.delta_pos hdeltaScalar current
  exact ⟨{
    grainLoss := schedule.scalarClosure.grainLoss
    stickyRho := pureWZ2SourceHorizontalInternalScale targetRho
    middleLoss := ownerOutput.middleLoss
    stickyLoss := schedule.stickyLoss
    outputEta := schedule.scalarClosure.outputEta
    inputEta := schedule.scalarClosure.inputEta
    logExponent := capability.logExponent
    croppedMassFraction :=
      Kakeya.realRpowENN delta schedule.scalarClosure.inputEta
    cwaNormalizationLoss := schedule.scalarClosure.sourceLossCeiling
    output_scale_eq := outer.final_scale_eq
    nonCWA := nonCWA
    scalar := scalar
  }⟩

end PureWZ2HierarchyReentrantOrdinaryCompletedPostOwnerReceipt

/-- Minimal remaining owner producer after every available pre-runtime scalar
choice and the public kernel call have been performed. -/
def PureWZ2HierarchyReentrantOrdinaryActualOwnerProducerAt
    (capability : PureWZ2PropStickyCapability) (sigma : ℝ) : Prop :=
  ∀ {outputLoss sourceLossCeiling : ℝ},
    ∀ schedule : PureWZ2HierarchyReentrantOrdinaryOwnerSchedule capability
        sigma outputLoss sourceLossCeiling,
      ∀ inputLoss : ℝ,
        0 < inputLoss → inputLoss ≤ sourceLossCeiling →
        ∀ delta : ℝ, 0 < delta → delta ≤ schedule.delta₀ →
          ∀ current : PureWZ2ReentrantGrainSource sigma inputLoss delta
              capability.normalizationExponent,
            ∀ targetRho : ℝ,
              delta ≤ targetRho → targetRho ≤ 1 →
              Real.rpow delta (1 - outputLoss) ≤ targetRho →
              targetRho ≤ Real.rpow delta outputLoss →
                ∀ outer : PureWZ2SourceHorizontalFlexibleOuterScaleData
                    delta targetRho schedule.stickyLoss outputLoss,
                  ∀ kernelOutput :
                      PureWZ2HierarchyReentrantOrdinaryKernelOutput
                        (current := current) schedule outer,
                    Nonempty
                      (PureWZ2HierarchyReentrantOrdinaryActualOwnerReceipt
                        (current := current) kernelOutput)

/-- Construction-independent owner output consumed by the ordinary geometry.
The first sticky datum is tied to the exact kernel output, while both owner
calls and their intermediate grain refinement are retained by `twoScale`. -/
def PureWZ2HierarchyReentrantOrdinaryOwnerOutputProducerAt
    (capability : PureWZ2PropStickyCapability) (sigma : ℝ) : Prop :=
  ∀ {outputLoss sourceLossCeiling : ℝ},
    ∀ schedule : PureWZ2HierarchyReentrantOrdinaryOwnerSchedule capability
        sigma outputLoss sourceLossCeiling,
      ∀ inputLoss : ℝ,
        0 < inputLoss → inputLoss ≤ sourceLossCeiling →
        ∀ delta : ℝ, 0 < delta → delta ≤ schedule.delta₀ →
          ∀ current : PureWZ2ReentrantGrainSource sigma inputLoss delta
              capability.normalizationExponent,
            ∀ targetRho : ℝ,
              delta ≤ targetRho → targetRho ≤ 1 →
              Real.rpow delta (1 - outputLoss) ≤ targetRho →
              targetRho ≤ Real.rpow delta outputLoss →
                ∀ outer : PureWZ2SourceHorizontalFlexibleOuterScaleData
                    delta targetRho schedule.stickyLoss outputLoss,
                  ∀ kernelOutput :
                      PureWZ2HierarchyReentrantOrdinaryKernelOutput
                        (current := current) schedule outer,
                    Nonempty
                      (PureWZ2HierarchyReentrantOrdinaryOwnerOutputReceipt
                        (current := current) kernelOutput)

/-- The legacy exact-truncation owner producer projects to the common owner
output without changing its selected witness. -/
theorem pureWZ2_reentrantOrdinaryOwnerOutputProducer_of_actual
    {capability : PureWZ2PropStickyCapability} {sigma : ℝ}
    (producer :
      PureWZ2HierarchyReentrantOrdinaryActualOwnerProducerAt capability sigma) :
    PureWZ2HierarchyReentrantOrdinaryOwnerOutputProducerAt capability sigma := by
  intro outputLoss sourceLossCeiling schedule inputLoss hinput hinputCeiling
    delta hdelta hdeltaSmall current targetRho hdeltaRho hrhoOne hrhoLower
    hrhoUpper outer kernelOutput
  rcases producer schedule inputLoss hinput hinputCeiling delta hdelta
      hdeltaSmall current targetRho hdeltaRho hrhoOne hrhoLower hrhoUpper outer
      kernelOutput with ⟨owner⟩
  exact owner.ownerOutput_nonempty

/-- Runtime source-slab AD leaf at the exact radius and loss selected by the
ordinary owner output. -/
def PureWZ2HierarchyReentrantOrdinarySourceRhoSlabADProducerAt
    (capability : PureWZ2PropStickyCapability) (sigma : ℝ) : Prop :=
  ∀ {outputLoss sourceLossCeiling : ℝ},
    ∀ schedule : PureWZ2HierarchyReentrantOrdinaryOwnerSchedule capability
        sigma outputLoss sourceLossCeiling,
      ∀ inputLoss : ℝ,
        0 < inputLoss → inputLoss ≤ sourceLossCeiling →
        ∀ delta : ℝ, 0 < delta → delta ≤ schedule.delta₀ →
          ∀ current : PureWZ2ReentrantGrainSource sigma inputLoss delta
              capability.normalizationExponent,
            ∀ targetRho : ℝ,
              delta ≤ targetRho → targetRho ≤ 1 →
              Real.rpow delta (1 - outputLoss) ≤ targetRho →
              targetRho ≤ Real.rpow delta outputLoss →
                ∀ outer : PureWZ2SourceHorizontalFlexibleOuterScaleData
                    delta targetRho schedule.stickyLoss outputLoss,
                  ∀ kernelOutput :
                      PureWZ2HierarchyReentrantOrdinaryKernelOutput
                        (current := current) schedule outer,
                    ∀ ownerOutput :
                        PureWZ2HierarchyReentrantOrdinaryOwnerOutputReceipt
                          (current := current) kernelOutput,
                      PureWZ2SourceRhoSlabADAt current
                        (pureWZ2SourceHorizontalInternalScale targetRho)
                        ownerOutput.middleLoss

end Kakeya.Assouad

end
