import Submission.MyLeanRepo.Kakeya.Assouad.PureWZ2.C2.SourceHorizontalResidueShading
import Submission.MyLeanRepo.Kakeya.Assouad.PureWZ2.C2.SourceWindowHeightPopularity
import Submission.MyLeanRepo.Kakeya.Assouad.PureWZ2.C2.ActiveCellShadowGrains
import Submission.MyLeanRepo.Kakeya.Assouad.PureWZ2.C2.StickyMultiplicity

/-!
# Outer-popular carrier for the ordinary source-horizontal step

The height popularity in WZ Lemma 5.5 is imposed on the source window before
the auxiliary graph is formed.  Later spatial selections must therefore be
intersected with that same height-popular union instead of silently restoring
the discarded heights.  This module records the resulting paper shading and
its equal-union partial active-cell shadow.

The graph carrier uses the complete source `delta`-cell envelope generated by
the height-popular region, not the non-cubical exact popular shading.  Points
of this envelope need not lie in the exact height region, but they remain
within one source-cell diameter of it.
-/

noncomputable section

namespace Kakeya.Assouad

open MeasureTheory Set

attribute [local instance] Classical.propDecidable

/-- The final spatial residue, restricted to the source-volume-popular height
region selected before the graph. -/
structure PureWZ2SourceHorizontalFixedBinPopularCarrierData
    {sigma inputLoss delta rho middleLoss stickyLoss : ℝ}
    {logExponent : ℕ}
    {source : PureWZ2QuantitativeGrainConfiguration sigma inputLoss delta}
    {twoScale : PureWZ2OneScaleTwoScaleStickyData
      source rho middleLoss stickyLoss logExponent}
    {pullback : PureWZ2TwoScaleCellPullbackData twoScale}
    {prepared : PureWZ2SourceCarrierPreparation pullback}
    {sourceWindow : PureWZ2SourceCarrierWindow prepared}
    (outerPopular : PureWZ2SourceWindowHeightPopularData
      sourceWindow (256 * rho))
    {window : PureWZ2SourceCarrierWindow prepared}
    {line : PureWZ2SourceHorizontalFixedBinData window}
    {parents : PureWZ2SourceHorizontalFixedBinParentData line}
    {selection : PureWZ2SourceHorizontalFixedBinYSelection parents}
    {residue : PureWZ2SourceHorizontalFixedBinYResidueData selection}
    (retained : PureWZ2SourceHorizontalFixedBinResidueShadingData residue) where
  shading : WZ1PaperTubeShading source.family
  carrier_eq : ∀ index, shading.carrier index =
    retained.shading.carrier index ∩ outerPopular.shading.union
  subshading_retained : PureWZ2PaperIsSubshading shading retained.shading
  subshading_source : PureWZ2PaperIsSubshading shading source.shading
  union_eq : shading.union =
    retained.shading.union ∩ outerPopular.shading.union
  point_near_height_region : ∀ point ∈ shading.union,
    ∃ anchor ∈ outerPopular.popular.heightRegion,
      dist point anchor < 2 * delta
  constant_multiplicity : shading.HasConstantMultiplicity
    twoScale.coarse.fineMultiplicity
    (2 * twoScale.coarse.fineMultiplicity)
  graphShadow : Kakeya.Streamlined.TubeShading
    (pureWZ2ActiveCellFamily retained.shading source.extremal.delta_pos)
  graphShadow_carrier_eq : ∀ index, graphShadow.carrier index =
    (pureWZ2ActiveCellShading retained.shading
      source.extremal.delta_pos).carrier index ∩
        shading.union
  graphShadow_sub : IsSubshading graphShadow
    (pureWZ2ActiveCellShading retained.shading source.extremal.delta_pos)
  graphShadow_union_eq : graphShadow.union = shading.union
  graphShadow_point_near_height_region : ∀ point ∈ graphShadow.union,
    ∃ anchor ∈ outerPopular.popular.heightRegion,
      dist point anchor < 2 * delta

/-- Build the exact ordinary pre-graph carrier.  This is the ordinary analogue
of `PureWZ2TerminalWindowHeightPopularData.toSourceCarrier`. -/
theorem PureWZ2SourceHorizontalFixedBinResidueShadingData.restrictToOuterPopularFixedBin
    {sigma inputLoss delta rho middleLoss stickyLoss : ℝ}
    {logExponent : ℕ}
    {source : PureWZ2QuantitativeGrainConfiguration sigma inputLoss delta}
    {twoScale : PureWZ2OneScaleTwoScaleStickyData
      source rho middleLoss stickyLoss logExponent}
    {pullback : PureWZ2TwoScaleCellPullbackData twoScale}
    {prepared : PureWZ2SourceCarrierPreparation pullback}
    {sourceWindow : PureWZ2SourceCarrierWindow prepared}
    (outerPopular : PureWZ2SourceWindowHeightPopularData
      sourceWindow (256 * rho))
    {window : PureWZ2SourceCarrierWindow prepared}
    {line : PureWZ2SourceHorizontalFixedBinData window}
    {parents : PureWZ2SourceHorizontalFixedBinParentData line}
    {selection : PureWZ2SourceHorizontalFixedBinYSelection parents}
    {residue : PureWZ2SourceHorizontalFixedBinYResidueData selection}
    (retained : PureWZ2SourceHorizontalFixedBinResidueShadingData residue) :
    Nonempty (PureWZ2SourceHorizontalFixedBinPopularCarrierData outerPopular retained) := by
  let region : Set Point3 := outerPopular.shading.union
  let shading : WZ1PaperTubeShading source.family :=
    { carrier := fun index => retained.shading.carrier index ∩ region
      measurable_carrier := fun index =>
        (retained.shading.measurable_carrier index).inter
          (measurableSet_shading_union outerPopular.shading)
      subset_body := fun index => Set.inter_subset_left.trans
        (retained.shading.subset_body index) }
  have hunion : shading.union =
      retained.shading.union ∩ outerPopular.shading.union := by
    ext point
    constructor
    · rintro ⟨index, hretained, hpopular⟩
      exact ⟨⟨index, hretained⟩, hpopular⟩
    · rintro ⟨⟨index, hretained⟩, hpopular⟩
      exact ⟨index, hretained, hpopular⟩
  have hsubRetained : PureWZ2PaperIsSubshading shading retained.shading :=
    fun _ => Set.inter_subset_left
  have hsubSource : PureWZ2PaperIsSubshading shading source.shading :=
    fun index => (hsubRetained index).trans (retained.subshading index)
  have hnear : ∀ point ∈ shading.union,
      ∃ anchor ∈ outerPopular.popular.heightRegion,
        dist point anchor < 2 * delta := by
    intro point hpoint
    apply outerPopular.shading_point_near_height_region point
    rw [hunion] at hpoint
    exact hpoint.2
  have hconstant : shading.HasConstantMultiplicity
      twoScale.coarse.fineMultiplicity
      (2 * twoScale.coarse.fineMultiplicity) := by
    have hambient := retained.constantMultiplicityFixedBin
    intro point hpoint
    have hmultiplicity := wholeCellRestriction_pointMultiplicity_eq
      (fun index => show shading.carrier index =
        retained.shading.carrier index ∩ region from rfl) hpoint
    rw [hmultiplicity]
    exact hambient point (by
      rcases hpoint with ⟨index, hindex⟩
      exact ⟨index, hindex.1⟩)
  let ambientShadow :=
    pureWZ2ActiveCellShading retained.shading source.extremal.delta_pos
  let graphShadow : Kakeya.Streamlined.TubeShading
      (pureWZ2ActiveCellFamily retained.shading source.extremal.delta_pos) :=
    { carrier := fun index => ambientShadow.carrier index ∩ shading.union
      measurable_carrier := fun index =>
        (ambientShadow.measurable_carrier index).inter
          (measurableSet_shading_union shading)
      subset_body := fun index => Set.inter_subset_left.trans
        (ambientShadow.subset_body index) }
  have hgraphUnion : graphShadow.union = shading.union := by
    have hsourceSubset : shading.union ⊆ retained.shading.union :=
      hsubRetained.union_subset
    have hambientUnion : ambientShadow.union = retained.shading.union :=
      pureWZ2ActiveCellShading_union retained.shading
        source.extremal.delta_pos retained.whole_cells
    apply Set.Subset.antisymm
    · rintro point ⟨_index, _hambient, hshading⟩
      exact hshading
    · intro point hshading
      have hambient : point ∈ ambientShadow.union := by
        rw [hambientUnion]
        exact hsourceSubset hshading
      rcases hambient with ⟨index, hindex⟩
      exact ⟨index, hindex, hshading⟩
  exact ⟨{
    shading := shading
    carrier_eq := fun _ => rfl
    subshading_retained := hsubRetained
    subshading_source := hsubSource
    union_eq := hunion
    point_near_height_region := hnear
    constant_multiplicity := hconstant
    graphShadow := graphShadow
    graphShadow_carrier_eq := fun _ => rfl
    graphShadow_sub := fun _ => Set.inter_subset_left
    graphShadow_union_eq := hgraphUnion
    graphShadow_point_near_height_region := by
      rw [hgraphUnion]
      exact hnear
  }⟩

/-- Install the restricted ordinary graph shadow while preserving every
whole-cell field of the residue carrier. -/
noncomputable def PureWZ2SourceHorizontalFixedBinResidueShadingData.withPopularGraphFixedBin
    {sigma inputLoss delta rho middleLoss stickyLoss : ℝ}
    {logExponent : ℕ}
    {source : PureWZ2QuantitativeGrainConfiguration sigma inputLoss delta}
    {twoScale : PureWZ2OneScaleTwoScaleStickyData
      source rho middleLoss stickyLoss logExponent}
    {pullback : PureWZ2TwoScaleCellPullbackData twoScale}
    {prepared : PureWZ2SourceCarrierPreparation pullback}
    {sourceWindow : PureWZ2SourceCarrierWindow prepared}
    {outerPopular : PureWZ2SourceWindowHeightPopularData
      sourceWindow (256 * rho)}
    {window : PureWZ2SourceCarrierWindow prepared}
    {line : PureWZ2SourceHorizontalFixedBinData window}
    {parents : PureWZ2SourceHorizontalFixedBinParentData line}
    {selection : PureWZ2SourceHorizontalFixedBinYSelection parents}
    {residue : PureWZ2SourceHorizontalFixedBinYResidueData selection}
    (retained : PureWZ2SourceHorizontalFixedBinResidueShadingData residue)
    (carrier : PureWZ2SourceHorizontalFixedBinPopularCarrierData outerPopular retained) :
    PureWZ2SourceHorizontalFixedBinResidueShadingData residue :=
  { retained with
    graphShadow := carrier.graphShadow
    graphShadow_sub := carrier.graphShadow_sub
    graphShadow_union_subset := by
      intro point hpoint
      have hambient :
          point ∈ (pureWZ2ActiveCellShading retained.shading
            source.extremal.delta_pos).union :=
        carrier.graphShadow_sub.union_subset hpoint
      rw [pureWZ2ActiveCellShading_union retained.shading
        source.extremal.delta_pos retained.whole_cells] at hambient
      exact hambient }

/-- Backwards-compatible outer-popular carrier on the maximal global bin. -/
abbrev PureWZ2SourceHorizontalPopularCarrierData
    {sigma inputLoss delta rho middleLoss stickyLoss : ℝ}
    {logExponent : ℕ}
    {source : PureWZ2QuantitativeGrainConfiguration sigma inputLoss delta}
    {twoScale : PureWZ2OneScaleTwoScaleStickyData
      source rho middleLoss stickyLoss logExponent}
    {pullback : PureWZ2TwoScaleCellPullbackData twoScale}
    {prepared : PureWZ2SourceCarrierPreparation pullback}
    {sourceWindow : PureWZ2SourceCarrierWindow prepared}
    (outerPopular : PureWZ2SourceWindowHeightPopularData
      sourceWindow (256 * rho))
    {window : PureWZ2SourceCarrierWindow prepared}
    {line : PureWZ2SourceHorizontalFixedLineData window}
    {parents : PureWZ2SourceHorizontalParentData line}
    {selection : PureWZ2SourceHorizontalYSelection parents}
    {residue : PureWZ2SourceHorizontalYResidueData selection}
    (retained : PureWZ2SourceHorizontalResidueShadingData residue) :=
  PureWZ2SourceHorizontalFixedBinPopularCarrierData outerPopular retained

/-- Compatibility wrapper for maximal-bin outer-popular restriction. -/
theorem PureWZ2SourceHorizontalResidueShadingData.restrictToOuterPopular
    {sigma inputLoss delta rho middleLoss stickyLoss : ℝ}
    {logExponent : ℕ}
    {source : PureWZ2QuantitativeGrainConfiguration sigma inputLoss delta}
    {twoScale : PureWZ2OneScaleTwoScaleStickyData
      source rho middleLoss stickyLoss logExponent}
    {pullback : PureWZ2TwoScaleCellPullbackData twoScale}
    {prepared : PureWZ2SourceCarrierPreparation pullback}
    {sourceWindow : PureWZ2SourceCarrierWindow prepared}
    (outerPopular : PureWZ2SourceWindowHeightPopularData
      sourceWindow (256 * rho))
    {window : PureWZ2SourceCarrierWindow prepared}
    {line : PureWZ2SourceHorizontalFixedLineData window}
    {parents : PureWZ2SourceHorizontalParentData line}
    {selection : PureWZ2SourceHorizontalYSelection parents}
    {residue : PureWZ2SourceHorizontalYResidueData selection}
    (retained : PureWZ2SourceHorizontalResidueShadingData residue) :
    Nonempty (PureWZ2SourceHorizontalPopularCarrierData outerPopular retained) :=
  retained.restrictToOuterPopularFixedBin outerPopular

/-- Compatibility wrapper for replacing the maximal-bin graph carrier. -/
noncomputable def PureWZ2SourceHorizontalResidueShadingData.withPopularGraph
    {sigma inputLoss delta rho middleLoss stickyLoss : ℝ}
    {logExponent : ℕ}
    {source : PureWZ2QuantitativeGrainConfiguration sigma inputLoss delta}
    {twoScale : PureWZ2OneScaleTwoScaleStickyData
      source rho middleLoss stickyLoss logExponent}
    {pullback : PureWZ2TwoScaleCellPullbackData twoScale}
    {prepared : PureWZ2SourceCarrierPreparation pullback}
    {sourceWindow : PureWZ2SourceCarrierWindow prepared}
    {outerPopular : PureWZ2SourceWindowHeightPopularData
      sourceWindow (256 * rho)}
    {window : PureWZ2SourceCarrierWindow prepared}
    {line : PureWZ2SourceHorizontalFixedLineData window}
    {parents : PureWZ2SourceHorizontalParentData line}
    {selection : PureWZ2SourceHorizontalYSelection parents}
    {residue : PureWZ2SourceHorizontalYResidueData selection}
    (retained : PureWZ2SourceHorizontalResidueShadingData residue)
    (carrier : PureWZ2SourceHorizontalPopularCarrierData outerPopular retained) :
    PureWZ2SourceHorizontalResidueShadingData residue :=
  retained.withPopularGraphFixedBin carrier

end Kakeya.Assouad

end
